package com.soul.patient.model.entity.enummaster;

public enum Relationship {
    AUNTY,
    BROTHER,
    BROTHER_IN_LAW,
    COLLEAGUE,
    COUSIN,
    DAUGHTER,
    DAUGHTER_IN_LAW,
    FATHER,
    FATHER_IN_LAW,
    FRIEND,
    GRAND_CHILD,
    GRAND_PARENT,
    GRAND_SON,
    GRANDMOTHER,
    GUARDIAN,
    HUSBAND,
    MOTHER,
    MOTHER_IN_LAW,
    NEPHEW,
    NEVUE,
    SELF,
    SISTER,
    SON,
    SON_IN_LAW,
    SPOUSE,
    UNCLE,
    WIFE
}
